openapi: 3.0.1
info:
  title: HelloWorldAPI
  description: API Definition of HelloWorldAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/helloworldapi
paths:
  /:
    get:
      responses:
        default:
          description: Default response
